In [1]:
# Numpy :- import numpy liabray 
import numpy as np

In [4]:
# array :-
# one dimensional
b=np.array([1,2,3,4,5,6])
# two dimensional
a=np.array([[1,2,3],[4,5,6]])
print(" one dimensional array :")
print(b)
print(" two dimensional array :")
print(a)


 one dimensional array :
[1 2 3 4 5 6]
 two dimensional array :
[[1 2 3]
 [4 5 6]]


In [5]:
# format :-the standard binary file format
# shape :-the number of elements in each dimension
a=np.array([[1,2,3],[4,5,6]])
print("shape of a {}".format(a.shape))


shape of a (2, 3)


In [6]:
# ndim :-represents the number of dimensions (axes) of the ndarray
a=np.array([[1,2,3],[4,5,6]])
print("ndim {}".format(a.ndim))


ndim 2


In [7]:
# size :-calculate the total elements or values  in the given array
a=np.array([[1,2,3],[4,5,6]])
print("size {}".format(a.size))


size 6


In [8]:
# dtype :-describes the bytes in the fixed-size block of memory
a=np.array([[1,2,3],[4,5,6]])
print("dtype {}".format(a.dtype))

dtype int64


In [9]:
# itemsize :-returns the size (in bytes) of each element of a NumPy array
a=np.array([[1,2,3],[4,5,6]])
print("itemsize {}".format(a.itemsize))


itemsize 8


In [10]:
# data :-
a=np.array([[1,2,3],[4,5,6]])
print("data {}".format(a.data))


data <memory at 0x7f2fdc06d5f0>


In [11]:
# sum :-returns the sum of array elements over the specified axis
a=np.array([[1,2,3],[4,5,6]])
print(a.sum())


21


In [12]:
# multiplication :-multiplication of two array
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
mul=np.dot(A,B)
print("multiplication :")
print(mul)


multiplication :
[[16 19]
 [26 31]]


In [13]:
# addition :-performs element-wise addition on NumPy arrays
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
ad=np.add(A,B)
print("addition :")
print(ad)


addition :
[[ 5  7]
 [ 8 10]]


In [14]:
# reshape:-changing the shape of an array
a=np.array([1,2,3,4,5,6])
re=a.reshape(2,3)
print(re)


[[1 2 3]
 [4 5 6]]


In [15]:
# maximum:-find the element-wise maximum of array elements
a=np.array([1,2,3,4,5,6])
print("maximum is ",a.max())


maximum is  6


In [16]:
# maximum along the axis
re=np.array([[1,2,3],[4,5,6]])
print("maximum is ",re.max(axis=1))


maximum is  [3 6]


In [17]:
# minimum :-find the element-wise minimum of array elements
a=np.array([1,2,3,4,5,6])
print("minimum is ",a.min())


minimum is  1


In [18]:
# minimum along the axis
re=np.array([[1,2,3],[4,5,6]])
print("minimum is ",re.min(axis=0))


minimum is  [1 2 3]


In [19]:
# square root:-calculate the positive square root of a number or the elements of an array
re=np.array([[1,4,9],[16,25,36]])
print(np.sqrt(re))


[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
# standard deviation :-calculates the standard deviation of given data along a specified axis
re=np.array([[1,4,9],[16,25,36]])
print("standard deviation ",np.std(re))


standard deviation  12.212243401148248
